# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchreader.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets,QtSql
from PyQt5.QtWidgets import QApplication, QMainWindow
from pymysql import *

class Ui_searchreader(object):
    def execute_sql(self, sql):
        try:
            self.cursor.execute(sql)
            self.db.commit()
        except Exception as err:
            print("err")
            self.db.rollback()

    def setupUi(self, searchreader):
        searchreader.setObjectName("searchreader")
        searchreader.resize(671, 533)
        self.pushButton = QtWidgets.QPushButton(searchreader)
        self.pushButton.setGeometry(QtCore.QRect(480, 59, 93, 28))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(searchreader)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 129, 93, 28))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableView = QtWidgets.QTableView(searchreader)
        self.tableView.setGeometry(QtCore.QRect(110, 230, 461, 201))
        self.tableView.setObjectName("tableView")
        self.widget = QtWidgets.QWidget(searchreader)
        self.widget.setGeometry(QtCore.QRect(110, 40, 271, 141))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.statusbar = QtWidgets.QStatusBar(searchreader)
        self.statusbar.setObjectName("statusbar")
        searchreader.setStatusBar(self.statusbar)
        self.retranslateUi(searchreader)
        self.pushButton_2.clicked.connect(searchreader.close)
        QtCore.QMetaObject.connectSlotsByName(searchreader)

        self.pushButton.clicked.connect(lambda: self.search_reader())

    def retranslateUi(self, searchreader):
        _translate = QtCore.QCoreApplication.translate
        searchreader.setWindowTitle(_translate("searchreader", "Form"))
        self.pushButton.setText(_translate("searchreader", "Submit"))
        self.pushButton_2.setText(_translate("searchreader", "Exit"))
        self.label.setText(_translate("searchreader", "ReaderId"))
        self.label_2.setText(_translate("searchreader", "Tel"))

    def search_reader(self):
        self.db = connect(host='localhost', port=3306, charset='utf8', database='Library', password='3303',
                          user='root')

        self.cursor = self.db.cursor()

        sql = "use Library"
        self.cursor.execute(sql)
        self.model = QtSql.QSqlTableModel()
        self.tableView.setModel(self.model)
        readerid = self.lineEdit.text()
        tel = self.lineEdit_2.text()
        print(readerid,tel)
        flag = False
        while True:
            if len(readerid) is 0 and len(tel) is not 0:
                sql = "select * from reader where TEL like '%s';" % ("%"+tel+"%")
                flag = True
                break
            elif len(readerid) is not 0 and  len(tel) is 0:
                sql = "select * from reader where readerid = '%d';" % int(readerid)
                flag = True
                break
            else:
                self.statusbar.showMessage("Please enter id or tel-phone", 3000)
                break
        if flag:
            print(sql)
            self.execute_sql(sql)
            data = self.cursor.fetchall()
            row = len(data)
            print(row)
            if row is not 0:
                model = QtGui.QStandardItemModel(row, len(data[0]))
                col = len(data[0])
                for i in range(row):
                    for j in range(len(data[0])):
                        if j is not 0 and j is not 3:
                            model.setItem(i, j, QtGui.QStandardItem(data[i][j]))
                        else:
                            if data[i][j] is None:
                                model.setItem(i, j, QtGui.QStandardItem(str(0)))
                            else:
                                model.setItem(i, j, QtGui.QStandardItem(str(data[i][j])))
                self.cursor.close()
                model.setHorizontalHeaderLabels(['ReaderId', 'Name', 'Sex', 'Age', 'Tel'])
                self.tableView.setModel(model)
            self.statusbar.showMessage("Query success！ Total " + str(row) + "data", 2000)
        else:
            self.statusbar.showMessage("Please enter information")





